name: Go
env:
  GO_VERSION: 1.20
run-name: "${{ github.run_id }}: Workflow run by @${{ github.actor }}"
on:
  workflow_dispatch: {}
  push:
    branches: [ "main", "dev" ]
jobs:
  test:
    runs-on: ubuntu-latest
    # if: false
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Set Up Go Environment"
      uses: actions/setup-go@v4
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: "Run Go Tests"
      run: go test -v main.go main_test.go
    - name: Upload Source Code
      uses: actions/upload-artifact@v4.3.5
      with:
        name: source-code
        path: "*.go"
  prod:
    needs: [test]
    if: false
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Download Source Code
      uses: actions/download-artifact@v4.1.8
      with:
        name: source-code
    - name: Release to Production
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: "${{ github.run_id }}"
        generate_release_notes: true
        name: "prod-${{ github.run_id }}"
        files: main.go
