name: No Cache
on:
  workflow_dispatch: {}

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      id: setup-go
      with:
        go-version: "1.22"
        cache: false
    - run: |
        GOFILE=$(go run main.go)
        echo "GOFILE=$GOFILE" >> $GITHUB_ENV
    - run: time go build ${{ env.GOFILE }}
