name: Inputs
on:
  workflow_dispatch:
    inputs:
      t:
        required: true
        type: string
      b:
        required: true
        type: string

jobs:
  do1:
    runs-on: ubuntu-latest
    if: false
    outputs:
      go-version: "${{ steps.setup-go.outputs.go-version }}"
      run-go-binary: "${{ steps.run-go-binary.outputs.RESPONSE_STATUS }}"
    permissions:
      issues: write
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Set Up Go Environment"
      uses: actions/setup-go@v4
      id: setup-go
      with:
        go-version: "1.20"
    - name: "Build Go File"
      run: go build main.go 
    - name: "Run Go Binary"
      id: run-go-binary
      # internally the app writes some env variables to $GITHUB_OUTPUT
      run: ./main -bear "${{ github.token }}" -title "${{ inputs.t }}" -body "${{ inputs.b }}" -repo "${{ github.repository }}"
  do2:
    runs-on: ubuntu-latest
    if: false
    needs: [do1]
    steps:
    - name: "Print Go Version Used"
      env:
        GO_VERSION: "${{ needs.do1.outputs.go-version }}"
      run: echo "$GO_VERSION"
    - name: "Print Response Status"
      env:
        RESPONSE_STATUS: "${{ needs.do1.outputs.run-go-binary }}"
      run: echo "$RESPONSE_STATUS"
