name: "df9f85cb3337a808f607"
on:
  workflow_dispatch: {}
jobs:
  group-1:
    runs-on: ubuntu-latest
    # continue-on-error: true
    strategy:
      matrix:
        env: [dev, stage, prod]
    steps:
      - if: ${{ matrix.env == 'stage' }}
        run: false
      - run: echo ${{ matrix.env }}
