name: Inputs
env:
  GO_VERSION: "1.20"
on:
  workflow_dispatch:
    inputs:
      t:
        required: true
        type: string
      b:
        required: true
        type: string

jobs:
  do1:
    runs-on: ubuntu-latest
    outputs:
      run-go-binary: "${{ steps.run-go-binary.outputs.RESPONSE_STATUS }}"
    permissions:
      issues: write
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Set Up Go Environment"
      uses: actions/setup-go@v4
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: "Build Go File"
      run: go build main.go 
    - name: "Run Go Binary"
      id: run-go-binary
      # internally the app writes some env variables to $GITHUB_OUTPUT
      run: ./main -bear "${{ github.token }}" -title "${{ inputs.t }}" -body "${{ inputs.b }}" -repo "${{ github.repository }}"
  do2:
    runs-on: ubuntu-latest
    needs: [do1]
    steps:
    - name: "Print Response Status"
      run: echo "${{ needs.do1.outputs.run-go-binary }}"
